version: '3.8'

services:
  mongo:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  cassandra:
    image: cassandra:latest
    container_name: cassandra
    ports:
      - "9042:9042"
    environment:
      CASSANDRA_KEYSPACE: "accommodation"

  auth-service:
    build: ./auth-service
    ports:
      - "8000:8000"
    depends_on:
      - mongo

  profile-service:
    build: ./profile-service
    ports:
      - "8001:8000"
    depends_on:
      - mongo

  accommodation-service:
    build: ./accommodation-service
    ports:
      - "8080:8080"
    depends_on:
      - cassandra
    environment:
      CASSANDRA_HOST: cassandra
      CASSANDRA_KEYSPACE: accommodation

  reservation-service:
    build: ./reservation-service
    ports:
      - "8081:8081"
    depends_on:
      - cassandra
    environment:
      CASSANDRA_HOST: cassandra
      CASSANDRA_KEYSPACE: reservations

volumes:
  mongo-data:
